import { useState } from 'react'
import { Link, useNavigate } from 'react-router'

type MfaStep = 'SETUP' | 'VERIFY' | 'SUCCESS'

export default function MfaPage() {
    const navigate = useNavigate()

    const [step, setStep] = useState<MfaStep>('SETUP')
    const [code, setCode] = useState('')
    const [error, setError] = useState('')

    const handleContinueToVerification = () => {
        setError('')
        setStep('VERIFY')
    }

    const handleVerify = () => {
        setError('')

        if (!/^\d{6}$/.test(code)) {
            setError('Enter a valid 6-digit verification code.')
            return
        }

        /*
         * Demo-only verification.
         *
         * Real MFA verification will later be handled
         * by Keycloak/backend security services.
         */
        setStep('SUCCESS')
    }

    const handleFinish = () => {
        navigate('/customer/security')
    }

    return (
        <div className="page-container">
            <Link to="/customer/security" className="back-link">
                ← Back to Security
            </Link>

            <div className="page-header">
                <h1>Two-Factor Authentication</h1>
                <p>
                    Add an extra layer of security to your SecurePay account.
                </p>
            </div>

            <div className="mfa-card">
                {step === 'SETUP' && (
                    <>
                        <div className="mfa-step-indicator">
                            <span className="active">1. Setup</span>
                            <span>2. Verify</span>
                            <span>3. Complete</span>
                        </div>

                        <h2>Set Up MFA</h2>

                        <p className="mfa-description">
                            Use an authenticator application to generate
                            verification codes for your SecurePay account.
                        </p>

                        <div className="mfa-setup-box">
                            <div className="mfa-qr-placeholder">
                                QR
                            </div>

                            <div>
                                <h3>Authenticator Setup</h3>
                                <p>
                                    Scan the setup QR code using your
                                    authenticator application.
                                </p>
                                <p>
                                    For this frontend demo, the actual
                                    Keycloak enrollment will be connected
                                    later.
                                </p>
                            </div>
                        </div>

                        <div className="mfa-actions">
                            <Link
                                to="/customer/security"
                                className="secondary-button"
                            >
                                Cancel
                            </Link>

                            <button
                                type="button"
                                className="primary-button"
                                onClick={handleContinueToVerification}
                            >
                                Continue
                            </button>
                        </div>
                    </>
                )}

                {step === 'VERIFY' && (
                    <>
                        <div className="mfa-step-indicator">
                            <span>1. Setup</span>
                            <span className="active">2. Verify</span>
                            <span>3. Complete</span>
                        </div>

                        <h2>Verify MFA</h2>

                        <p className="mfa-description">
                            Enter the 6-digit code generated by your
                            authenticator application.
                        </p>

                        <div className="form-group">
                            <label htmlFor="mfa-code">
                                Verification Code
                            </label>

                            <input
                                id="mfa-code"
                                type="text"
                                inputMode="numeric"
                                maxLength={6}
                                placeholder="000000"
                                value={code}
                                onChange={(event) => {
                                    setCode(
                                        event.target.value.replace(
                                            /\D/g,
                                            '',
                                        ),
                                    )
                                    setError('')
                                }}
                            />

                            {error && (
                                <p className="form-error">
                                    {error}
                                </p>
                            )}
                        </div>

                        <div className="mfa-actions">
                            <button
                                type="button"
                                className="secondary-button"
                                onClick={() => setStep('SETUP')}
                            >
                                Back
                            </button>

                            <button
                                type="button"
                                className="primary-button"
                                onClick={handleVerify}
                            >
                                Verify & Enable
                            </button>
                        </div>
                    </>
                )}

                {step === 'SUCCESS' && (
                    <>
                        <div className="mfa-step-indicator">
                            <span>1. Setup</span>
                            <span>2. Verify</span>
                            <span className="active">3. Complete</span>
                        </div>

                        <div className="mfa-success">
                            <div className="mfa-success-icon">✓</div>

                            <h2>MFA Enabled</h2>

                            <p>
                                Two-factor authentication has been enabled
                                for your SecurePay account.
                            </p>
                        </div>

                        <div className="mfa-actions">
                            <button
                                type="button"
                                className="primary-button"
                                onClick={handleFinish}
                            >
                                Back to Security
                            </button>
                        </div>
                    </>
                )}
            </div>
        </div>
    )
}