spring.application.name=securepay-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/securepay
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

app.jwtSecret=${JWT_SECRET}

keycloak.server-url=http://localhost:8082
keycloak.realm=securepay
keycloak.client-id=securepay-backend
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}