spring.application.name=securepay-backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/securepay
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
#  Sahil1234

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false